baseURL: 'http://example.org/'
languageCode: en-us
title: Rigo Moran
theme: tien
markup:
  highlight:
    style: onedark
menus:
  main:
  - name: Ideas
    pageRef: /ideas
    weight: 10
  - name: Til
    pageRef: /til
    weight: 20
  - name: Projects
    pageRef: /projects
    weight: 30

params:
  # Add svg logo to assets folder
  logo: 'logo'

  # social accounts
  # socials:
  # github: 'github_id'
  # gitlab: 'gitlab_id'
  # twitter: 'twitter_id'
  # linkedin: 'linkedin_id'
  # mastadon: 'mastadon_id'
  # hashnode: 'hashnode_id'
  # bluesky: 'bluesky_id'
  # stack-overflow: 'stack_overflow_id'
  
  socials:
    - name: twitter
      url: 'https://twitter.com/rigomoran_'
    - name: linkedin
      url: 'https://www.linkedin.com/in/rodrigomoran'
    - name: github
      url: 'https://github.com/phantompunk'
    - name: stack-overflow
      url: 'https://stackoverflow.com/users/5776586/rodrigo-moran'
    - name: hashnode
      url: 'https://hashnode.com/@rigomoran'

