baseURL: 'http://example.org/'
languageCode: en-us
title: My New Hugo Site
theme: tien
params:
  categories:
    - Web Development
    - Blogging
    - Web Design
  mainSections:
    - blog
    - til
