baseURL: 'http://example.org/'
languageCode: en-us
title: Rigo Moran
theme: tien
markup:
  highlight:
    style: base16-snazzy
params:
  socials:
    - name: twitter
      url: 'https://twitter.com/rigomoran_'
    - name: linkedin
      url: 'https://www.linkedin.com/in/rodrigomoran'
    - name: github
      url: 'https://github.com/phantompunk'
    - name: stack-overflow
      url: 'https://stackoverflow.com/users/5776586/rodrigo-moran'
    - name: hashnode
      url: 'https://hashnode.com/@rigomoran'
  categories:
    - Web Development
    - Web Design
  mainSections:
    - ideas
    - til
